#!/bin/bash

efi_kexts_path="/Volumes/EFI/EFI/CLOVER/kexts/Other/"
extentions_kexts_path="/Library/Extensions/"

echo ""
echo "FIXER script"
echo "This script will fix the audio jack issue"
echo ""
echo "-- Mounting EFI"
sudo diskutil mount EFI > /dev/null 2>&1
echo "-- Copying Kexts from EFI to extensions folder"
sudo cp -R $efi_kexts_path* $extentions_kexts_path
echo "-- Unmounting EFI"
sudo diskutil unmount EFI > /dev/null 2>&1
echo "-- Repair permissions and rebuilding cache"
sudo chmod -Rf 755 /S*/L*/E* > /dev/null 2>&1
sudo chmod -Rf 755 /L*/E* > /dev/null 2>&1
sudo chown -Rf 0:0 /S*/L*/E* > /dev/null 2>&1
sudo chown -Rf 0:0 /L*/E* > /dev/null 2>&1
sudo kextcache -i / > /dev/null 2>&1
echo ""
echo "FINISHED"
echo ""