#!/bin/bash

efi_kexts_path="/Volumes/EFI/EFI/CLOVER/kexts/Other/"
extentions_kexts_path="/Library/Extensions/"

echo ""
echo "AUDIO FIXER script"
echo "This script will fix the audio jack issue"
echo ""
echo "-- Mounting EFI"
sudo diskutil mount EFI > /dev/null 2>&1
echo "-- Copying Kexts from EFI to extensions folder"
sudo cp -R $efi_kexts_path* $extentions_kexts_path
echo "-- Unmounting EFI"
sudo diskutil unmount EFI > /dev/null 2>&1
sudo ./RES/REBUILD
echo ""
echo "Finished, Reboot to see changes"
echo ""