#!/bin/bash

efi_kexts_path="/Volumes/EFI/EFI/CLOVER/kexts/Other/"
extentions_kexts_path="/Library/Extensions/"
voodo_i2c_kext_name="VoodooI2C.kext"
voodo_i2chid_kext_name="VoodooI2CHID.kext"
kexts_path="RES/mouse_kexts/"

echo ""
echo "MOUSE FIXER script"
echo "This script will fix the double clicking with mouse"
echo "Disclaimer: It will ruin the trackpad, to revert execute the REVERT_MOUSE script"
echo ""
echo "-- Mounting EFI"
sudo diskutil mount EFI > /dev/null 2>&1
echo "-- Deleting old Kexts from EFI kexts folder"
sudo rm -rf $efi_kexts_path/$voodo_i2c_kext_name $efi_kexts_path/$voodo_i2chid_kext_name
echo "-- Deleting old Kexts from extensions folder"
sudo rm -rf $extentions_kexts_path/$voodo_i2c_kext_name $extentions_kexts_path/$voodo_i2chid_kext_name
echo "-- Copying new kexts to EFI kexts and extensions folder"
sudo cp -R $kexts_path/* $efi_kexts_path
sudo cp -R $kexts_path/* $extentions_kexts_path
echo "-- Unmounting EFI"
sudo diskutil unmount EFI > /dev/null 2>&1
sudo ./REBUILD
echo ""
echo "Finished, Reboot to see changes"
echo ""