#!/bin/bash
echo "-- Repair permissions and rebuilding cache"
sudo chmod -Rf 755 /S*/L*/E* > /dev/null 2>&1
sudo chmod -Rf 755 /L*/E* > /dev/null 2>&1
sudo chown -Rf 0:0 /S*/L*/E* > /dev/null 2>&1
sudo chown -Rf 0:0 /L*/E* > /dev/null 2>&1
sudo kextcache -i / > /dev/null 2>&1